#!/usr/bin/env Rscript
# Phase 4 (Redirects): write the Cloudflare Pages redirects file of the static forum archive.
#
#   Rscript R/02b_redirects.R [--raw DIR] [--site DIR]
#
# Reads --raw (default "raw", made by R/01b_redact.R) and the pages of --site (default "dist", built by
# R/02_build.R); there is no network access. Writes --site/_redirects, so that the URLs of the live forum
# keep working. Every rule is a 301; a source never ends with a slash, a destination is a page of the
# archive and always does:
#   1  site pages    /latest /categories /top /new /unread /posts /about /faq /guidelines /tos /privacy /tags
#                    /badges /directory /groups /users -> /      and      /search -> /search/
#   2  topics        /t/{slug}/{id}, /t/{id}, /t/{slug} and /t/{slug}/{id}/{n} for every post number n of the
#                    topic in raw/ -> /t/{slug}/{id}/, plus #post-n for n >= 2 when the topic page renders that
#                    post (system events are not rendered); post numbers raw/ does not have get no rule
#   3  categories    /c/{id}, /c/{path}, /c/{path}/{id} and, for subcategories, /c/{slug}/{id} -> /c/{path}/{id}/
#   4  stale slugs   /t/{old slug}/{id} for links inside posts that name a slug the topic no longer has
#   5  dynamic       /u/* /users/* /g/* /groups/* /tag/* /tags/* /badges/* -> /   (user pages are out of scope)
# The slug-only rule /t/{slug} is left out (and reported) when two topics share the slug or the slug is a
# number, which would read as a topic id. The output is deterministic: stable order, no dates and no paths,
# "\n" line endings. A build replaces the whole of --site, so this runs after every build.
#
# Safety: --raw must be a redacted copy (manifest.json with derived_from == "raw_verbatim" and a redaction
# block, plus redaction-report.json) and --site must hold sitemap.xml and index.html (R/02_build.R's own
# output). The finished text is parsed back and checked before anything is written: at most 2000 static and
# 100 dynamic rules, at most 1000 characters per line, only the characters allowed, no duplicate source, no
# source that would shadow a page or a file of --site (Pages follows a redirect even where a file exists),
# every destination page and every #post-n anchor present in --site, no destination that is a source itself.
# A failure writes nothing and leaves an existing _redirects as it was; the file is written to
# _redirects.part and renamed. An existing _redirects must be this script's own earlier output.

FORUM_HOST       <- "discourse.igelsociety.org"
RAW_DEFAULT      <- "raw"
SITE_DEFAULT     <- "dist"
MANIFEST_FILE    <- "manifest.json"
REDACTION_REPORT <- "redaction-report.json"
SITEMAP_FILE     <- "sitemap.xml"
REDIRECTS_FILE   <- "_redirects"
MARKER           <- "# Generated by R/02b_redirects.R"    # first line of the file: this script's own output

STATUS       <- "301"
VALID_STATUS <- c("301", "302", "303", "307", "308")
MAX_STATIC   <- 2000L                  # Cloudflare Pages: static rules, dynamic rules, characters per line
MAX_DYNAMIC  <- 100L
MAX_LINE     <- 1000L

# Pages of the live forum without a counterpart in the archive, and the prefixes that get a splat rule.
HOME_PAGES  <- c("latest", "categories", "top", "new", "unread", "posts", "about", "faq", "guidelines", "tos",
                 "privacy", "tags", "badges", "directory", "groups", "users")
SPLAT_PAGES <- c("u", "users", "g", "groups", "tag", "tags", "badges")

GROUPS <- c("site pages", "topics and posts", "categories", "stale topic slugs",
            "user, group, tag and badge pages (dynamic)")
GROUP_NOTES <- c(
  "# Group 1: pages of the live forum without a counterpart here go to the home page; /search keeps its own page.",
  "# Group 2: topics: /t/{slug}/{id}, /t/{id}, /t/{slug} and one rule per post number, with #post-n where the topic page has that post.",
  "# Group 3: categories: /c/{id}, /c/{path}, /c/{path}/{id} and, for subcategories, /c/{slug}/{id}.",
  "# Group 4: stale topic slugs: links between posts that name a slug the topic no longer has.",
  "# Group 5: dynamic, last: user, group, tag and badge pages are out of scope and go to the home page.")

SLUG_RE   <- "^[A-Za-z0-9._~-]+$"
# What the rules may consist of: a static source is a path without a trailing slash, a dynamic one ends in
# /*, a destination is a page URL (always with a trailing slash) and may end in #post-N.
SOURCE_RE <- "^/(?:[A-Za-z0-9._~-]+/)*[A-Za-z0-9._~-]+$"
SPLAT_RE  <- "^/(?:[A-Za-z0-9._~-]+/)+\\*$"
DEST_RE   <- "^/(?:[A-Za-z0-9._~-]+/)*(?:#post-[0-9]+)?$"
# Every post of a topic page (templates/topic.html). A post's own text cannot spoof it: the build escapes "<"
# in text and drops every id attribute.
ANCHOR_RE <- "<article class=\"post\" id=\"post-([0-9]+)\">"
# An href value: double-quoted, single-quoted or bare (not data-href, xlink:href ...).
HREF_RE   <- "(?i)(?<![\\w:-])href\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s\"'>]+))"
URL_RE    <- "(?s)^(?:([A-Za-z][A-Za-z0-9+.-]*):)?(?://([^/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?$"

USAGE <- "Usage: Rscript R/02b_redirects.R [--raw DIR] [--site DIR]
  --raw DIR   redacted copy of the harvest to read (default: raw)
  --site DIR  built site to write _redirects into (default: dist); it must hold sitemap.xml and index.html"

# ---- helpers -----------------------------------------------------------------------------------
# Parsed JSON is always read with [[ ]]: `$` partial-matches.

`%||%` <- function(x, y) if (is.null(x)) y else x

say <- function(fmt, ...) message("[redirects] ", if (...length() > 0) sprintf(fmt, ...) else fmt)

abort <- function(...) {
  stop(structure(class = c("redirects_abort", "error", "condition"),
                 list(message = paste0(...), call = NULL)))
}

parse_args <- function(argv) {
  opts <- list(raw = RAW_DEFAULT, site = SITE_DEFAULT)
  flags <- c("--raw" = "raw", "--site" = "site")
  i <- 1L
  while (i <= length(argv)) {
    a <- argv[i]
    flag <- sub("=.*$", "", a)
    if (flag %in% names(flags)) {
      if (grepl("=", a, fixed = TRUE)) {
        v <- sub("^[^=]*=", "", a)
      } else {
        if (i >= length(argv)) abort(flag, " needs a value\n", USAGE)
        i <- i + 1L
        v <- argv[i]
      }
      opts[[flags[[flag]]]] <- v
    } else if (a %in% c("-h", "--help")) {
      cat(USAGE, "\n")
      quit(save = "no", status = 0L)
    } else {
      abort("Unknown argument: ", a, "\n", USAGE)
    }
    i <- i + 1L
  }
  if (!nzchar(opts$raw) || !nzchar(opts$site)) abort("--raw and --site must not be empty")
  opts
}

shown <- function(x, n = 5L) {
  paste0(paste(utils::head(x, n), collapse = ", "), if (length(x) > n) sprintf(", ... (%d in all)", length(x)) else "")
}

# ---- files and text ----------------------------------------------------------------------------

read_bytes <- function(path) readBin(path, "raw", n = file.size(path))

bytes_to_text <- function(bytes, what) {
  txt <- tryCatch(rawToChar(bytes), error = function(e) abort(what, " contains a NUL byte"))
  Encoding(txt) <- "UTF-8"
  if (!validUTF8(txt)) abort(what, " is not valid UTF-8")
  txt
}

read_text <- function(path, what = path) gsub("\r\n?", "\n", bytes_to_text(read_bytes(path), what))

read_json_file <- function(path) {
  tryCatch(jsonlite::read_json(path, simplifyVector = FALSE),
           error = function(e) abort("Cannot parse JSON file ", path, ": ", conditionMessage(e)))
}

list_tree <- function(dir) {
  entries <- fs::dir_ls(dir, recurse = TRUE, all = TRUE)
  if (length(entries) == 0L) return(list(files = character(), other = character()))
  type <- as.character(fs::file_info(entries)$type)
  rel <- as.character(fs::path_rel(entries, start = dir))
  list(files = rel[type == "file"], other = rel[!type %in% c("file", "directory")])
}

# ---- the inputs: guards ------------------------------------------------------------------------

# Only a redacted copy may be published: manifest.json says what it was derived from and how it was
# redacted, and the redaction report must exist (the same test as R/02_build.R).
verify_redacted <- function(raw) {
  mpath <- file.path(raw, MANIFEST_FILE)
  if (!file.exists(mpath)) abort(raw, " has no ", MANIFEST_FILE, ": not a harvest or a redacted copy of one")
  manifest <- read_json_file(mpath)
  if (!identical(manifest[["derived_from"]], "raw_verbatim") ||
      !is.list(manifest[["redaction"]]) || length(manifest[["redaction"]]) == 0L) {
    abort(raw, " is not a redacted copy (its ", MANIFEST_FILE, " lacks derived_from == \"raw_verbatim\" and a redaction block); ",
          "run R/01b_redact.R and use its output. Refusing to work from unredacted data.")
  }
  if (!file.exists(file.path(raw, REDACTION_REPORT))) {
    abort(raw, " is not a redacted copy (no ", REDACTION_REPORT, "). Refusing to work from unredacted data.")
  }
  manifest
}

# --site must be the output of R/02_build.R.
verify_site <- function(site) {
  if (!dir.exists(site)) abort("--site ", site, " is not a directory")
  need <- c(SITEMAP_FILE, "index.html")
  missing <- need[!file.exists(file.path(site, need))]
  if (length(missing) > 0L) {
    abort(site, " is not a build of R/02_build.R (no ", paste(missing, collapse = " and "), "); run the build first")
  }
}

# An existing _redirects may only be replaced if this script wrote it: its first line starts with MARKER.
check_target <- function(path) {
  if (!file.exists(path) && !fs::is_link(path)) return("absent")
  if (fs::is_link(path) || !fs::is_file(path)) abort(path, " is a symbolic link or not a plain file; refusing to touch it")
  if (!identical(readBin(path, "raw", n = nchar(MARKER)), charToRaw(MARKER))) {
    abort(path, " exists but this script did not write it (its first line does not start with \"", MARKER,
          "\"); refusing to overwrite it. Move it away if it is to be replaced.")
  }
  "ours"
}

# ---- raw/: categories, topics -------------------------------------------------------------------

check_slug <- function(slug, what) {
  if (!is.character(slug) || length(slug) != 1L || !grepl(SLUG_RE, slug)) {
    abort(what, " has a slug that cannot go into a redirect rule: '", paste(slug, collapse = " "), "'")
  }
  slug
}

# One record per category (id, slug, parent_slug, path = "slug" or "parent/slug"), sorted by id, as
# R/02_build.R flattens categories.json.
load_categories <- function(raw) {
  json <- read_json_file(file.path(raw, "categories.json"))
  top <- json[["category_list"]][["categories"]]
  if (!is.list(top) || length(top) == 0L) abort("categories.json has no category_list$categories")
  rows <- list()
  visit <- function(node, parent_slug) {
    id <- node[["id"]]
    if (!is.numeric(id) || length(id) != 1L) abort("A category in categories.json has no id")
    id <- as.integer(id)
    slug <- check_slug(node[["slug"]], paste("category", id))
    rows[[length(rows) + 1L]] <<- list(id = id, slug = slug, parent_slug = parent_slug,
                                       path = paste(c(parent_slug, slug), collapse = "/"))
    kids <- node[["subcategory_list"]]
    if (is.list(kids) && length(kids) > 0L) {
      if (!is.null(parent_slug)) abort("Category ", id, " has subcategories of its own; one level of subcategories is supported")
      for (kid in kids) visit(kid, slug)
    }
  }
  for (node in top) visit(node, NULL)
  ids <- vapply(rows, function(r) r$id, 1L)
  if (anyDuplicated(ids)) abort("categories.json lists category ", shown(ids[duplicated(ids)]), " twice")
  rows[order(ids)]
}

# One record per topic, sorted by id: its slug, the post numbers of topic/{id}.json plus every
# topic/{id}-posts-{k}.json, and the cooked HTML of all those posts (for the stale-slug scan).
load_topics <- function(raw) {
  dir <- file.path(raw, "topic")
  if (!dir.exists(dir)) abort(raw, " has no topic/ directory")
  files <- list.files(dir, pattern = "\\.json$")
  main <- files[grepl("^[0-9]+\\.json$", files)]
  chunks <- files[grepl("^[0-9]+-posts-[0-9]+\\.json$", files)]
  stray <- setdiff(files, c(main, chunks))
  if (length(stray) > 0L) abort("Unexpected files in ", dir, ": ", shown(stray))
  main <- main[order(as.integer(sub("\\.json$", "", main)))]
  ids <- as.integer(sub("\\.json$", "", main))
  chunk_topic <- as.integer(sub("-posts-.*$", "", chunks))
  chunk_k <- as.integer(sub("^.*-posts-([0-9]+)\\.json$", "\\1", chunks))
  if (length(setdiff(chunk_topic, ids)) > 0L) abort("Chunk files without a topic file: topic ", shown(setdiff(chunk_topic, ids)))
  lapply(seq_along(ids), function(i) {
    id <- ids[i]
    t <- read_json_file(file.path(dir, main[i]))
    if (!identical(as.integer(t[["id"]] %||% NA), id)) abort(main[i], " does not hold topic ", id)
    slug <- check_slug(t[["slug"]], paste("topic", id))
    posts <- t[["post_stream"]][["posts"]]
    if (!is.list(posts)) abort(main[i], " has no post_stream$posts")
    mine <- which(chunk_topic == id)
    for (j in mine[order(chunk_k[mine])]) {
      extra <- read_json_file(file.path(dir, chunks[j]))[["post_stream"]][["posts"]]
      if (!is.list(extra)) abort(chunks[j], " has no post_stream$posts")
      posts <- c(posts, extra)
    }
    numbers <- vapply(posts, function(p) as.integer(p[["post_number"]] %||% NA), 1L)
    if (anyNA(numbers)) abort("Topic ", id, " has a post without a post_number")
    list(id = id, slug = slug, numbers = sort(unique(numbers)),
         cooked = vapply(posts, function(p) as.character(p[["cooked"]] %||% ""), ""))
  })
}

# ---- the built site ----------------------------------------------------------------------------

# The files of --site (this script's own output is not part of the site).
site_index <- function(dir) {
  list(dir = dir, files = setdiff(list_tree(dir)$files, c(REDIRECTS_FILE, paste0(REDIRECTS_FILE, ".part"))))
}

# "/t/a/1/" -> "t/a/1/index.html", "/" -> "index.html"
page_of <- function(path) paste0(sub("^/", "", path), "index.html")

page_anchors <- function(html) {
  m <- regmatches(html, gregexpr(ANCHOR_RE, html, perl = TRUE))[[1]]
  as.integer(sub(ANCHOR_RE, "\\1", m, perl = TRUE))
}

# The post numbers each topic page renders, by topic id. A page that is missing is left out here and
# reported by the self-check. A page without any post anchor means the template changed; a page that
# renders a post raw/ does not have means the site was not built from this raw/.
read_anchors <- function(site, topics) {
  anchors <- list()
  problems <- character()
  for (t in topics) {
    rel <- page_of(sprintf("/t/%s/%d/", t$slug, t$id))
    if (!rel %in% site$files) next
    found <- page_anchors(read_text(file.path(site$dir, rel)))
    if (length(found) == 0L) {
      problems <- c(problems, sprintf("%s has no <article class=\"post\" id=\"post-N\"> (did templates/topic.html change?)", rel))
    } else if (!all(found %in% t$numbers)) {
      problems <- c(problems, sprintf("%s renders post %s, which raw/ does not have", rel, shown(setdiff(found, t$numbers))))
    }
    anchors[[as.character(t$id)]] <- found
  }
  if (length(problems) > 0L) abort("The pages of the site do not fit raw/ (build the site from this raw/): ", shown(problems, 3L))
  anchors
}

# ---- stale slugs --------------------------------------------------------------------------------

# The path of a link into the forum (absolute, protocol-relative or root-relative), else NA; the same
# test as classify_url() in R/02_build.R.
forum_path <- function(u) {
  u <- gsub("[\t\n\r]", "", trimws(u))
  m <- regmatches(u, regexec(URL_RE, u, perl = TRUE))[[1]]
  if (length(m) != 6L) return(NA_character_)
  scheme <- tolower(m[2])
  host <- tolower(m[3])
  inside <- if (scheme %in% c("http", "https") || (scheme == "" && nzchar(host))) host == FORUM_HOST
            else scheme == "" && startsWith(m[4], "/")
  if (inside) m[4] else NA_character_
}

# The slug and id a /t/ path names, read the way route_topic() in R/02_build.R reads it: /t/{id}[/{n}] and
# /t/{slug} name no slug; /t/{slug}/{id}[/{n}] does; /t/{a}/{b} with two numbers is {slug}/{id} only if
# topic b has the slug a (otherwise it is /t/{id}/{n}). NULL for anything else.
topic_link <- function(path, slug_of) {
  segs <- strsplit(path, "/", fixed = TRUE)[[1]]
  segs <- segs[nzchar(segs)]
  if (length(segs) < 2L || segs[1] != "t") return(NULL)
  rest <- segs[-1]
  num <- grepl("^[0-9]+$", rest)
  n <- length(rest)
  if ((n == 2L && num[2] && !num[1]) || (n == 3L && num[2] && num[3])) {
    list(slug = rest[1], id = rest[2])
  } else if (n == 2L && num[1] && num[2] && identical(slug_of[[rest[2]]], rest[1])) {
    list(slug = rest[1], id = rest[2])
  } else {
    NULL
  }
}

# Links in the posts to an archived topic whose slug differs from the topic's own: one (id, slug) per
# distinct pair, sorted by id. Slugs that cannot go into a rule are set aside (and reported), not fatal:
# they are text some member typed.
find_stale_slugs <- function(topics) {
  slug_of <- stats::setNames(lapply(topics, function(t) t$slug), vapply(topics, function(t) as.character(t$id), ""))
  ids <- character()
  slugs <- character()
  n_links <- 0L
  for (t in topics) {
    found <- unlist(regmatches(t$cooked, gregexpr(HREF_RE, t$cooked, perl = TRUE)))
    for (u in sub(HREF_RE, "\\1\\2\\3", found, perl = TRUE)) {
      path <- forum_path(u)
      link <- if (is.na(path)) NULL else topic_link(path, slug_of)
      if (is.null(link) || is.null(slug_of[[link$id]])) next
      n_links <- n_links + 1L
      if (!identical(link$slug, slug_of[[link$id]])) {
        ids <- c(ids, link$id)
        slugs <- c(slugs, link$slug)
      }
    }
  }
  # sprintf, not paste: paste() of zero-length vectors is not zero-length
  fresh <- !duplicated(sprintf("%s %s", ids, slugs))
  ids <- ids[fresh]
  slugs <- slugs[fresh]
  ok <- grepl(SLUG_RE, slugs)
  ord <- order(as.integer(ids[ok]), slugs[ok], method = "radix")
  list(id = as.integer(ids[ok])[ord], slug = slugs[ok][ord], unusable = sprintf("topic %s: %s", ids[!ok], slugs[!ok]),
       links_with_slug = n_links, stale_pairs = length(ids))
}

# ---- the rules ---------------------------------------------------------------------------------

new_rules <- function() list(source = character(), dest = character(), group = integer())

add_rules <- function(rules, group, source, dest) {
  dest <- rep_len(dest, length(source))
  rules$source <- c(rules$source, source)
  rules$dest <- c(rules$dest, dest)
  rules$group <- c(rules$group, rep(group, length(source)))
  rules
}

# All rules of the five groups, in file order, and counts for the report. `anchors` holds the post numbers
# each topic page renders; `stale` is find_stale_slugs().
make_rules <- function(topics, cats, anchors, stale) {
  rules <- new_rules()
  rules <- add_rules(rules, 1L, paste0("/", HOME_PAGES), "/")
  rules <- add_rules(rules, 1L, "/search", "/search/")

  slugs <- vapply(topics, function(t) t$slug, "")
  skip_slug <- slugs %in% slugs[duplicated(slugs)] | grepl("^[0-9]+$", slugs)
  notes <- list(slug_only_skipped = slugs[skip_slug], post_rules = 0L, post_fragments = 0L, post_first = 0L,
                post_unrendered = 0L)
  for (i in seq_along(topics)) {
    t <- topics[[i]]
    canon <- sprintf("/t/%s/%d/", t$slug, t$id)
    n <- t$numbers
    frag <- n >= 2L & n %in% anchors[[as.character(t$id)]]
    own <- c(sprintf("/t/%s/%d", t$slug, t$id), sprintf("/t/%d", t$id), if (!skip_slug[i]) sprintf("/t/%s", t$slug))
    rules <- add_rules(rules, 2L, c(own, sprintf("/t/%s/%d/%d", t$slug, t$id, n)),
                       c(rep(canon, length(own)), sprintf("%s%s", canon, ifelse(frag, sprintf("#post-%d", n), ""))))
    notes$post_rules <- notes$post_rules + length(n)
    notes$post_fragments <- notes$post_fragments + sum(frag)
    notes$post_first <- notes$post_first + sum(n == 1L)
    notes$post_unrendered <- notes$post_unrendered + sum(n >= 2L & !frag)
  }

  for (k in cats) {
    canon <- sprintf("/c/%s/%d/", k$path, k$id)
    own <- c(sprintf("/c/%d", k$id), sprintf("/c/%s", k$path), sprintf("/c/%s/%d", k$path, k$id),
             if (!is.null(k$parent_slug)) sprintf("/c/%s/%d", k$slug, k$id))
    rules <- add_rules(rules, 3L, own, canon)
  }

  by_id <- stats::setNames(topics, vapply(topics, function(t) as.character(t$id), ""))
  real <- vapply(stale$id, function(i) by_id[[as.character(i)]]$slug, "")
  rules <- add_rules(rules, 4L, sprintf("/t/%s/%d", stale$slug, stale$id), sprintf("/t/%s/%d/", real, stale$id))

  rules <- add_rules(rules, 5L, paste0("/", SPLAT_PAGES, "/*"), "/")
  list(rules = rules, notes = notes)
}

is_dynamic <- function(source) grepl("[*:]", source)

# The lines of the file: a header with the counts per group, then one comment line and the rules per group.
render_redirects <- function(rules) {
  dynamic <- is_dynamic(rules$source)
  header <- c(
    paste0(MARKER, " from raw/ and the built pages: do not edit by hand, run it again (make redirects)."),
    "# Redirects of the static archive of discourse.igelsociety.org on Cloudflare Pages, so that the URLs of the live",
    "# forum keep working. Every rule is a permanent redirect (301). A source never ends with a slash; a destination",
    "# is a page of the archive and always does. The static rules come first, the dynamic ones last.",
    sprintf("# Rules: %d = %d static (limit %d) + %d dynamic (limit %d); %d destinations end in a #post-n fragment.",
            length(dynamic), sum(!dynamic), MAX_STATIC, sum(dynamic), MAX_DYNAMIC, sum(grepl("#", rules$dest, fixed = TRUE))),
    sprintf("#   %d  %s  %d", seq_along(GROUPS), format(GROUPS), tabulate(rules$group, nbins = length(GROUPS))))
  body <- unlist(lapply(seq_along(GROUPS), function(g) {
    i <- rules$group == g
    c(GROUP_NOTES[g], sprintf("%s %s %s", rules$source[i], rules$dest[i], STATUS))
  }), use.names = FALSE)
  c(header, body)
}

# ---- the checks on the finished text -------------------------------------------------------------

parse_rules <- function(lines) {
  body <- trimws(lines)
  body <- body[nzchar(body) & !startsWith(body, "#")]
  fields <- strsplit(body, "[ \t]+")
  bad <- lengths(fields) != 3L
  if (any(bad)) abort("Self-check failed: lines that are not 'source destination status': ", shown(body[bad]))
  list(source = vapply(fields, `[[`, "", 1L), dest = vapply(fields, `[[`, "", 2L),
       status = vapply(fields, `[[`, "", 3L))
}

under_any <- function(x, prefixes) {
  hit <- rep(FALSE, length(x))
  for (p in prefixes) hit <- hit | startsWith(x, p)
  hit
}

# What the site answers with a file and no redirect: a file at its own path, x.html at /x (clean URL), and
# x/index.html at /x/ ("pages"; "/" is the home page).
site_urls <- function(files) {
  index <- basename(files) == "index.html"
  html <- endsWith(files, ".html") & !index
  list(served = c(paste0("/", files), paste0("/", sub("\\.html$", "", files[html]))),
       pages = paste0("/", sub("index\\.html$", "", files[index])))
}

# Parses the lines back and checks them against the site; aborts with every problem found. Returns the
# numbers for the report.
check_rules <- function(lines, site) {
  rules <- parse_rules(lines)
  src <- rules$source
  dst <- rules$dest
  dynamic <- is_dynamic(src)
  prefix <- sub("\\*$", "", src[dynamic])
  path <- sub("#.*$", "", dst)
  urls <- site_urls(site$files)
  problems <- character()
  flag <- function(what, x) if (length(x) > 0L) problems <<- c(problems, paste0(what, ": ", shown(x)))

  # limits, characters, shapes
  flag(sprintf("more than %d static rules", MAX_STATIC), if (sum(!dynamic) > MAX_STATIC) sum(!dynamic))
  flag(sprintf("more than %d dynamic rules", MAX_DYNAMIC), if (sum(dynamic) > MAX_DYNAMIC) sum(dynamic))
  flag(sprintf("lines longer than %d characters (line numbers)", MAX_LINE), which(nchar(lines, type = "bytes") > MAX_LINE))
  flag("lines with characters other than printable ASCII (line numbers)", which(grepl("[^\\x20-\\x7e]", lines, perl = TRUE)))
  flag("statuses Cloudflare Pages does not accept", setdiff(unique(rules$status), VALID_STATUS))
  source_ok <- ifelse(dynamic, grepl(SPLAT_RE, src, perl = TRUE), grepl(SOURCE_RE, src, perl = TRUE))
  flag("sources that are not a path without a trailing slash (or /path/*) of [A-Za-z0-9._~-]", src[!source_ok])
  flag("destinations that are not a page URL ending in a slash (optionally with #post-N)", dst[!grepl(DEST_RE, dst, perl = TRUE)])
  flag("sources that occur twice", unique(src[duplicated(src)]))

  # destinations: the page and the anchor must exist
  missing <- !page_of(path) %in% site$files
  flag("destinations that are not pages of the site", unique(path[missing]))
  has_frag <- grepl("#", dst, fixed = TRUE)
  for (p in unique(path[has_frag & !missing])) {
    f <- dst[has_frag & path == p]
    want <- suppressWarnings(as.integer(sub("^[^#]*#post-", "", f)))
    have <- page_anchors(read_text(file.path(site$dir, page_of(p))))
    flag(sprintf("fragments that are not in the page %s", p), f[is.na(want) | !want %in% have])
  }

  # loops: a destination is never a source (a splat counts for everything below its prefix)
  flag("destinations that are also a source (a redirect could loop)", unique(path[path %in% src | under_any(path, prefix)]))
  flag("static sources that a dynamic rule matches too (the order would decide)", src[!dynamic][under_any(src[!dynamic], prefix)])

  # shadows: Pages follows a redirect even where a file exists. /x for x/index.html is the normal case of
  # groups 2 and 3 (Pages redirects /x to /x/ itself) and harmless as long as the rule leads to /x/.
  alias <- paste0(src, "/") %in% urls$pages & path != paste0(src, "/")
  flag("sources that would shadow a file or page of the site", src[!dynamic & (src %in% urls$served | alias)])
  taken <- c(urls$served, urls$pages)
  flag("dynamic sources that would shadow files or pages of the site", src[dynamic][vapply(prefix, function(p) any(startsWith(taken, p)), NA)])

  if (length(problems) > 0L) abort("Self-check failed, nothing was written:\n  - ", paste(problems, collapse = "\n  - "))
  list(static = sum(!dynamic), dynamic = sum(dynamic), fragments = sum(has_frag), longest = max(nchar(lines, type = "bytes")))
}

# ---- writing -----------------------------------------------------------------------------------

write_redirects <- function(lines, target) {
  part <- paste0(target, ".part")
  if (fs::is_link(part) || (file.exists(part) && !fs::is_file(part))) abort(part, " is a symbolic link or not a plain file; refusing to touch it")
  bytes <- charToRaw(paste0(paste(lines, collapse = "\n"), "\n"))
  on.exit(unlink(part), add = TRUE)
  writeBin(bytes, part)
  if (!identical(read_bytes(part), bytes)) abort("Could not write ", part, " completely")
  if (!file.rename(part, target)) abort("Cannot move ", part, " to ", target)
  invisible(bytes)
}

# ---- run ---------------------------------------------------------------------------------------

run_redirects <- function(opts) {
  started <- Sys.time()
  raw <- opts$raw
  say("raw=%s site=%s", raw, opts$site)
  if (!dir.exists(raw)) abort("--raw ", raw, " is not a directory")
  manifest <- verify_redacted(raw)
  say("%s is a redacted copy (%d redactions in %d files)", raw,
      as.integer(manifest[["redaction"]][["total_redactions"]] %||% 0L), as.integer(manifest[["redaction"]][["files_modified"]] %||% 0L))
  verify_site(opts$site)
  target <- as.character(fs::path(opts$site, REDIRECTS_FILE))
  state <- check_target(target)

  cats <- load_categories(raw)
  topics <- load_topics(raw)
  site <- site_index(opts$site)
  say("categories: %d (%d top-level, %d sub); topics: %d; post numbers: %d; files in the site: %d", length(cats),
      sum(vapply(cats, function(k) is.null(k$parent_slug), NA)), sum(vapply(cats, function(k) !is.null(k$parent_slug), NA)),
      length(topics), sum(vapply(topics, function(t) length(t$numbers), 1L)), length(site$files))
  anchors <- read_anchors(site, topics)
  stale <- find_stale_slugs(topics)
  say("links to archived topics that name a slug: %d; %d name a stale slug (%d rules)", stale$links_with_slug,
      stale$stale_pairs, length(stale$id))
  for (i in seq_along(stale$id)) say("  stale slug: /t/%s/%d", stale$slug[i], stale$id[i])
  if (length(stale$unusable) > 0L) say("WARNING: stale slugs that cannot go into a rule were left out: %s", shown(stale$unusable))

  made <- make_rules(topics, cats, anchors, stale)
  lines <- render_redirects(made$rules)
  checked <- check_rules(lines, site)
  say("self-checks passed")
  write_redirects(lines, target)

  per_group <- tabulate(made$rules$group, nbins = length(GROUPS))
  for (g in seq_along(GROUPS)) say("group %d %s: %d rules", g, GROUPS[g], per_group[g])
  notes <- made$notes
  say("posts: %d rules, %d with a #post-n fragment, %d for post 1, %d for posts the topic page does not render",
      notes$post_rules, notes$post_fragments, notes$post_first, notes$post_unrendered)
  if (length(notes$slug_only_skipped) > 0L) {
    say("WARNING: no /t/{slug} rule for %d topics whose slug is shared or a number: %s", length(notes$slug_only_skipped), shown(notes$slug_only_skipped))
  }
  say("static %d of %d, dynamic %d of %d; longest line %d of %d characters; %d fragments", checked$static, MAX_STATIC,
      checked$dynamic, MAX_DYNAMIC, checked$longest, MAX_LINE, checked$fragments)
  say("%s %s (%d lines, sha256 %s)", if (state == "ours") "replaced" else "wrote", target, length(lines),
      digest::digest(file = target, algo = "sha256"))
  say("DONE in %.0f s", as.numeric(difftime(Sys.time(), started, units = "secs")))
  invisible(list(lines = lines, rules = made$rules, notes = notes, stale = stale, checked = checked))
}

main <- function(argv = commandArgs(trailingOnly = TRUE)) {
  ok <- tryCatch({
    run_redirects(parse_args(argv))
    TRUE
  }, redirects_abort = function(e) {
    message("\nREDIRECTS ABORTED: ", conditionMessage(e))
    FALSE
  }, error = function(e) {
    message("\nREDIRECTS FAILED (unexpected error): ", conditionMessage(e))
    FALSE
  })
  if (!ok) quit(save = "no", status = 1L)
}

if (sys.nframe() == 0L) main()
